name: Static Analysis

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  lint-check:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint check
        run: npm run lint

  format-check:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Prettier check
        run: npm run format:check

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint-check
      - format-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build
